print('Print e')
e=[1,1,1,1,2,3,4,4,4,5,5,6,7]
print(e.append(2))
print(e)
print('-----------------')
print('remove')
print('print f')
f=[10,1,2,3,4,5,6,7]
# f.remove(3)
print(f)
print('-----------------')
print('pop remueve el elemento indice de la lista')
print(f.pop(4))
print(f)
print('-----------------')
print('extend e-f')

print(e)
print(e.extend(f))
print('-----------------')
print('sort - reordena la lista')
f.sort()
print(f)
print('-----------------')
f.reverse()
print(f)
print('-----------------')
f.clear()
print(f)
print('-----------------')
copia_e = e.copy()
print(copia_e)
